LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Rotationlocker
LOCAL_SRC_FILES := 3rdparty/Rotationlocker.apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APP
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Limelight
LOCAL_SRC_FILES := 3rdparty/Limelight.apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APP
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SuperUser 
LOCAL_SRC_FILES := 3rdparty/SuperUser/Superuser.apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APP
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
include $(BUILD_PREBUILT)
